### ISSUE TITLE
Publish command not working

### ISSUE THREAD

**Issue by pastorsj** [apiaryio/apiary-client#151]
Let me preface this by saying I am not an experienced Ruby developer, so I am not sure whether this is a Ruby version problem or something different.
I just updated to Ruby 2.4.0 using rvm and when I run this command:
```
apiary publish --api-name=some-api
```
I receive this error
```
/Users/sampastoriza/.rvm/gems/ruby-2.4.0/gems/rest-client-1.8.0/lib/restclient/request.rb:163:in `fetch': key not found: :ciphers (KeyError)
	from /Users/sampastoriza/.rvm/gems/ruby-2.4.0/gems/rest-client-1.8.0/lib/restclient/request.rb:163:in `initialize'
	from /Users/sampastoriza/.rvm/gems/ruby-2.4.0/gems/rest-client-1.8.0/lib/restclient/request.rb:41:in `new'
	from /Users/sampastoriza/.rvm/gems/ruby-2.4.0/gems/rest-client-1.8.0/lib/restclient/request.rb:41:in `execute'
	from /Users/sampastoriza/.rvm/gems/ruby-2.4.0/gems/rest-client-1.8.0/lib/restclient.rb:69:in `post'
	from /Users/sampastoriza/.rvm/gems/ruby-2.4.0/gems/apiaryio-0.8.0/lib/apiary/command/publish.rb:77:in `query_apiary'
	from /Users/sampastoriza/.rvm/gems/ruby-2.4.0/gems/apiaryio-0.8.0/lib/apiary/command/publish.rb:53:in `publish_on_apiary'
	from /Users/sampastoriza/.rvm/gems/ruby-2.4.0/gems/apiaryio-0.8.0/lib/apiary/command/publish.rb:41:in `execute'
	from /Users/sampastoriza/.rvm/gems/ruby-2.4.0/gems/apiaryio-0.8.0/lib/apiary/cli.rb:45:in `publish'
	from /Users/sampastoriza/.rvm/gems/ruby-2.4.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /Users/sampastoriza/.rvm/gems/ruby-2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/sampastoriza/.rvm/gems/ruby-2.4.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /Users/sampastoriza/.rvm/gems/ruby-2.4.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /Users/sampastoriza/.rvm/gems/ruby-2.4.0/gems/apiaryio-0.8.0/bin/apiary:5:in `<top (required)>'
	from /Users/sampastoriza/.rvm/gems/ruby-2.4.0/bin/apiary:23:in `load'
	from /Users/sampastoriza/.rvm/gems/ruby-2.4.0/bin/apiary:23:in `<main>'
	from /Users/sampastoriza/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/sampastoriza/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `<main>'
```
Any thoughts? Thanks!

**Comment by tu1ly** [comment]
thx for the report. it seems to be rest-client-1.8.0 & Ruby 2.4.0 problem - https://github.com/rest-client/rest-client/issues/600 . we'll update rest-client in next release

**Comment by nrathi** [comment]
Do you plan on resolving this?

**Comment by bidva** [comment]
any news on this ?

**Comment by tu1ly** [comment]
https://github.com/apiaryio/apiary-client/pull/164
