### ISSUE TITLE
Publishing failing while using docker

### ISSUE THREAD

**Issue by femz12** [apiaryio/apiary-client#181]
I run `docker run -e APIARY_API_KEY="<key>"  --volume ~/Downloads/test:/tmp apiaryio/client publish --message="testing" --path="/tmp/apiary.apib" --api-name="femz12"`

I got error could this be a temporary error? Or I am doing something wrong here.

```
> /usr/lib/ruby/2.2.0/json/common.rb:155:in `parse': 757: unexpected token at '<HTML><HEAD> (JSON::ParserError)
> <TITLE>Service Unavailable</TITLE>
> </HEAD><BODY>
> <H1>Service Unavailable - Zero size object</H1>
> The server is temporarily unable to service your request.  Please try again
> later.<P>
> Reference&#32;&#35;15&#46;5dc83017&#46;1547498888&#46;c8c2f383
> </BODY></HTML>
> '
> 	from /usr/lib/ruby/2.2.0/json/common.rb:155:in `parse'
> 	from /usr/lib/ruby/gems/2.2.0/gems/apiaryio-0.5.1/lib/apiary/command/publish.rb:77:in `rescue in query_apiary'
> 	from /usr/lib/ruby/gems/2.2.0/gems/apiaryio-0.5.1/lib/apiary/command/publish.rb:67:in `query_apiary'
> 	from /usr/lib/ruby/gems/2.2.0/gems/apiaryio-0.5.1/lib/apiary/command/publish.rb:52:in `publish_on_apiary'
> 	from /usr/lib/ruby/gems/2.2.0/gems/apiaryio-0.5.1/lib/apiary/command/publish.rb:40:in `execute'
> 	from /usr/lib/ruby/gems/2.2.0/gems/apiaryio-0.5.1/lib/apiary/cli.rb:41:in `publish'
> 	from /usr/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
> 	from /usr/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
> 	from /usr/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
> 	from /usr/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
> 	from /usr/lib/ruby/gems/2.2.0/gems/apiaryio-0.5.1/bin/apiary:5:in `<top (required)>'
> 	from /usr/bin/apiary:23:in `load'
> 	from /usr/bin/apiary:23:in `<main>'
> 
```

**Comment by abtris** [comment]
Looks like that you get error page instead response from server. Do you try later if problem is still valid?
